### ISSUE TITLE
Logged messages do not always appear in the order sent

### ISSUE THREAD

**Issue by klardotsh** [Greums/logging-slackhandler#2]
In the event of code that looks like, say,

```python
my_logger.info('Something')
my_logger.info('Something2')
# ... do some things
my_logger.info('lol')
my_logger.error('another thing')
```

I'll very often get messages out of order in my Slack channel. This is, I assume, because of worker threads being dispatched without regard to the state of prior entries in the queue (if there even is one? I haven't had a chance to read through the code)?

**Comment by greums** [comment]
Messages are processed in a FIFO order from the queue, but due to network latency, Slack response time or message length, concurrent messages can appear in a different order in destination channel than the one you sent them.

I think this behaviour is mostly visible when calling logger multiple times in a row, which should not be a common user case.

If message order is a requirement, you can define `SlackHandler` with a pool size of `1`, so that only one thread will process the queue:

```
slack_handler = SlackHandler('YOUR_WEBHOOK_URL', pool_size=1) 
```

**Comment by greums** [comment]
I close this issue if it's okay for you.

If you have any remark or question just let me know !

**Comment by klardotsh** [comment]
`pool_size=1` led to losing some messages (I'm not sure what the deal was - maybe an issue with the `atexit` handler?), so I've moved off of this to blocking `slackclient` calls.

Thanks for your work and your help regardless!

**Comment by greums** [comment]
Yes, that's an issue I didn't address for now: I only wait for current thread task to be completed on exit, messages in tasks queue are lost (very problematic indeed when running with a single thread).

I modified this behaviour to wait for queue to be fully processed *and* jobs completed when exiting.
